package render

import (
	"encoding/json"
	"fmt"
	"html"
	"io"

	"jdiff/internal/diff"
	"jdiff/internal/patch"
	"jdiff/internal/version"
)

// renderHTML produces an interactive, single-file, zero-dependency HTML diff report.
func renderHTML(w io.Writer, result *diff.DiffResult, opts Options) error {
	oldLabel := html.EscapeString(opts.OldPath)
	if oldLabel == "" {
		oldLabel = "old.json"
	}
	newLabel := html.EscapeString(opts.NewPath)
	if newLabel == "" {
		newLabel = "new.json"
	}

	summary := result.Summary()
	patchDoc := patch.Generate(result)
	patchJSON, _ := json.MarshalIndent(patchDoc, "", "  ")

	changesJSON, _ := json.Marshal(result.Changes)

	htmlContent := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jdiff Report: %s vs %s</title>
  <style>
    :root {
      --bg: #0d1117;
      --card-bg: #161b22;
      --border: #30363d;
      --text: #c9d1d9;
      --text-muted: #8b949e;
      --added: #238636;
      --added-bg: rgba(35, 134, 54, 0.15);
      --removed: #da3633;
      --removed-bg: rgba(218, 54, 51, 0.15);
      --modified: #d29922;
      --modified-bg: rgba(210, 153, 34, 0.15);
      --accent: #58a6ff;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace; }
    body { background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.5; }
    .container { max-width: 1200px; margin: 0 auto; }
    header { border-bottom: 1px solid var(--border); padding-bottom: 1.5rem; margin-bottom: 1.5rem; display: flex; justify-content: space-between; align-items: center; }
    h1 { font-size: 1.5rem; font-weight: 600; color: #fff; }
    .meta { font-size: 0.875rem; color: var(--text-muted); margin-top: 0.25rem; }
    .badges { display: flex; gap: 0.75rem; margin-bottom: 1.5rem; }
    .badge { padding: 0.4rem 0.8rem; border-radius: 6px; font-weight: 600; font-size: 0.875rem; display: inline-flex; align-items: center; gap: 0.4rem; }
    .badge-added { background: var(--added-bg); color: #3fb950; border: 1px solid rgba(63, 185, 80, 0.3); }
    .badge-removed { background: var(--removed-bg); color: #f85149; border: 1px solid rgba(248, 81, 73, 0.3); }
    .badge-modified { background: var(--modified-bg); color: #e3b341; border: 1px solid rgba(227, 179, 65, 0.3); }
    .controls { display: flex; gap: 1rem; margin-bottom: 1.5rem; }
    input.search { flex: 1; padding: 0.6rem 1rem; background: var(--card-bg); border: 1px solid var(--border); border-radius: 6px; color: #fff; font-size: 0.9rem; }
    input.search:focus { outline: none; border-color: var(--accent); }
    .btn { padding: 0.6rem 1rem; background: var(--card-bg); border: 1px solid var(--border); border-radius: 6px; color: var(--text); cursor: pointer; font-weight: 500; }
    .btn:hover { background: #21262d; }
    .card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 6px; overflow: hidden; margin-bottom: 1rem; }
    .card-header { padding: 0.75rem 1rem; background: rgba(0,0,0,0.2); border-bottom: 1px solid var(--border); font-size: 0.875rem; font-weight: 600; display: flex; justify-content: space-between; }
    .change-item { padding: 1rem; border-bottom: 1px solid var(--border); font-family: monospace; font-size: 0.9rem; }
    .change-item:last-child { border-bottom: none; }
    .diff-path { font-weight: 600; color: var(--accent); margin-bottom: 0.5rem; }
    .diff-val-old { color: #f85149; background: var(--removed-bg); padding: 0.2rem 0.5rem; border-radius: 4px; display: inline-block; margin-right: 0.5rem; }
    .diff-val-new { color: #3fb950; background: var(--added-bg); padding: 0.2rem 0.5rem; border-radius: 4px; display: inline-block; }
    footer { text-align: center; margin-top: 3rem; font-size: 0.8rem; color: var(--text-muted); }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div>
        <h1>jdiff Visualizer</h1>
        <div class="meta">Comparing <strong>%s</strong> &rarr; <strong>%s</strong></div>
      </div>
      <div class="meta">Generated by jdiff %s</div>
    </header>

    <div class="badges">
      <div class="badge badge-added">Added: %d</div>
      <div class="badge badge-removed">Removed: %d</div>
      <div class="badge badge-modified">Modified: %d</div>
      <div class="badge" style="background: var(--card-bg); border: 1px solid var(--border)">Total: %d</div>
    </div>

    <div class="controls">
      <input type="text" id="searchInput" class="search" placeholder="Search paths or values...">
      <button class="btn" onclick="copyPatch()">Copy JSON Patch</button>
    </div>

    <div class="card">
      <div class="card-header">
        <span>Structural Changes</span>
        <span id="matchCount">%d changes</span>
      </div>
      <div id="changesList"></div>
    </div>

    <footer>
      jdiff &bull; Standalone Zero-Dependency JSON Structural Diff Engine
    </footer>
  </div>

  <script>
    const changes = %s;
    const patchDoc = %s;

    function renderChanges(filter = "") {
      const container = document.getElementById("changesList");
      container.innerHTML = "";
      const q = filter.toLowerCase();
      let matched = 0;

      changes.forEach(c => {
        const pathStr = c.Path.segments ? c.Path.segments.map(s => s.Key || s.Index).join(".") : JSON.stringify(c.Path);
        const oldValStr = JSON.stringify(c.OldValue);
        const newValStr = JSON.stringify(c.NewValue);

        if (q && !pathStr.toLowerCase().includes(q) && !oldValStr.toLowerCase().includes(q) && !newValStr.toLowerCase().includes(q)) {
          return;
        }

        matched++;
        const div = document.createElement("div");
        div.className = "change-item";
        
        let valHTML = "";
        if (c.Type === "MODIFIED") {
          valHTML = '<span class="diff-val-old">- ' + escapeHTML(oldValStr) + '</span><span class="diff-val-new">+ ' + escapeHTML(newValStr) + '</span>';
        } else if (c.Type === "ADDED") {
          valHTML = '<span class="diff-val-new">+ ' + escapeHTML(newValStr) + '</span>';
        } else if (c.Type === "REMOVED") {
          valHTML = '<span class="diff-val-old">- ' + escapeHTML(oldValStr) + '</span>';
        }

        div.innerHTML = '<div class="diff-path">' + escapeHTML(pathStr) + ' <span style="font-size:0.75rem; color:var(--text-muted);">(' + c.Type + ')</span></div>' + valHTML;
        container.appendChild(div);
      });

      document.getElementById("matchCount").textContent = matched + " changes";
    }

    function escapeHTML(str) {
      if (!str) return "";
      return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    }

    function copyPatch() {
      navigator.clipboard.writeText(JSON.stringify(patchDoc, null, 2)).then(() => {
        alert("JSON Patch copied to clipboard!");
      });
    }

    document.getElementById("searchInput").addEventListener("input", (e) => {
      renderChanges(e.target.value);
    });

    renderChanges();
  </script>
</body>
</html>`,
		oldLabel, newLabel, oldLabel, newLabel, version.Short(),
		summary.Added, summary.Removed, summary.Modified, summary.Total(),
		summary.Total(),
		string(changesJSON),
		string(patchJSON),
	)

	_, err := fmt.Fprint(w, htmlContent)
	return err
}
